### ISSUE TITLE
This is more like a question (how does blox handle resource createion/cleanup/reclaim) 

### ISSUE THREAD

**Issue by etsangsplk** [blox/blox#126]
Since there are multiple resources embedded (vpc,subnet etc etc), when blox brings down a cluster how does it make sure those are also released but not leaving as dangling. And how does it handle if it cannot resolve those it itself?

**Comment by narehayrapetyan** [comment]
@etsangsplk what do you mean by when blox brings down a cluster? Do you mean the ECS cluster it's running on? Blox resources are set up using cloudformation and cloudformation is what's responsible for setup and cleanup. If you delete the cloudformation stack you can configure your policy so it removes all the associated resources.

**Comment by poojamaiya** [comment]
@etsangsplk, did you have any follow-up questions here?

**Comment by poojamaiya** [comment]
@etsangsplk, I'm resolving this issue since there isn't any actionable items to pick up from this. Please feel free to reopen if you think otherwise or have any more questions. Thanks!
