### ISSUE TITLE
Delete environment

### ISSUE THREAD

**Issue by narehayrapetyan** [blox/blox#134]
Currently the delete environment API deletes the environment regardless of whether the environment has running tasks. Add a check to prevent the deletion of an "active" environment, ie one that has running tasks, and provide a force delete environment option that stops the tasks before deleting the environment. 

This will also help with test cleanup as deleting the environment after the test runs will clean up its artifacts (tasks started by the environment) as well.

**Comment by shubharao** [comment]
Handled in design of Blox v1.0. Details [here](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#deleting-an-environment)
