### ISSUE TITLE
Cluster state service information gets stale

### ISSUE THREAD

**Issue by narehayrapetyan** [blox/blox#137]
When cluster state service runs for a while and multiple end to end and integration tests are run against it, it seems to get stale and not have up to date information about the latest instances. Needs investigation.

**Comment by narehayrapetyan** [comment]
Cluster state does not always clean up old instances and tasks. When running daemon scheduler e2e tests multiple times, they hang on "when I kill all tasks" even when there are no tasks running because CSS thinks there are running tasks. Same with instances.

**Comment by kylbarnes** [comment]
Fix applied in #179. We previously had no timeout values set on our SQS consumer, which would cause it to block indefinitely on any networking issues. This change sets the http timeout to 30s, which allows the sqs consumer to recover and continue polling

**Comment by kylbarnes** [comment]
Released in v0.2.1.
