### ISSUE TITLE
Design for update, rollback and delete environments and deployments

### ISSUE THREAD

**Issue by poojamaiya** [blox/blox#146]
Update environments, deployments
Delete environments
Stop deployments
Rollback deployments

**Comment by hridyeshpant** [comment]
@poojamaiya  this is very much required.
I deployed environment with taskdef with version 1, all the ecs instances are running that taskdef version. But now i am not able to deploy new version 2 of that taskdef.
So i deleted old environment, create new environment with new task def version and deployed it.
The schedule api is returning that new version 2 is successfully running, but all the instances are still running version 1. 

{
  "items": [
    {
      "environmentName": "test",
      "failedInstances": [],
      "id": "dac71a7f-7c1d-4e83-8d0b-acda8fcf8ece",
      "status": "running",
      "taskDefinition": "arn:aws:ecs:us-west-2:XYZ:task-definition/my_task:2"
    }
  ]
}

do you have any workaround to deploy new taskdef version, i am kind of blocked now the old version 1 have some bug and want to deploy new version 2?

**Comment by hridyeshpant** [comment]
@poojamaiya if i killed that ecs task for a instances, scheduler is deploying the new version for that instances only. so i need to manually need to stop task for all my 96 instance to pick new version each time. 
Do you have any plan to rollout Update environments/deployments soon?

**Comment by poojamaiya** [comment]
@hridyeshpant Thanks for the feedback. We are actively working on scoping down this piece of the scheduler and getting a design in place. We'll have an update for you shortly.

In order to get the get your instances to stop the old version and pick up the new ones, I'd do the following to stop all tasks first.

(1) List all the deployments in the environment using the Blox List Deployments API. Today there can be only one deployment. Note the id field which is the deployment id.
`curl -X "GET" http://localhost:2000/v1/environments/<ENVIRONMENT_NAME>/deployments`

(2) List all tasks using the ECS List Tasks API setting the started-by field to the deployment id you retrieved in step 1. You can use the AWS cli to do this.
`aws ecs list-tasks --started-by <DEPLOYMENT_ID>`

(3) Stop all tasks listed in the previous step using the ECS Stop Task API.
`aws ecs stop-task --task <TASK_ARN>`

We realize that this is a bunch of manual steps and have prioritized getting update-deployments working in the daemon scheduler. We are continually working on improving Blox. Any feedback is welcome!

**Comment by pmanwatkar** [comment]
@poojamaiya can we have some ETA for this. This would help us.

**Comment by ajosuarez** [comment]
@pmanwatkar we anticipate publishing a design for public comment in the next few weeks. we'll share the link in this issue once ready as well.

**Comment by hridyeshpant** [comment]
@simplycloud is there any update on this feature?

**Comment by cjpetrus** [comment]
@simplycloud  we're all waiting.

**Comment by hridyeshpant** [comment]
@cjpetrus not sure if Amazon are actively following and contributing in Blox project any more. 
Last checking i am seeing is happened in March month.
@poojamaiya @simplycloud do you have any info about the future road map of Blox.?

**Comment by ajosuarez** [comment]
@cjpetrus @hridyeshpant yes -- we are actively working on the project. we've been finalizing a design proposal that we hope to share as soon as next week regarding dameon scheduler enhancements! thanks for your interest in Blox!

**Comment by shubharao** [comment]
See details in v1.0 design [here](blox/docs/daemon_design.md)
