### ISSUE TITLE
Automate running unit tests

### ISSUE THREAD

**Issue by poojamaiya** [blox/blox#149]
Travis? Jenkins?

**Comment by poojamaiya** [comment]
Reopening this because `make build` with the commit #150 that introduces travis changes undoes the swagger changes brought in by the commit.

**Comment by narehayrapetyan** [comment]
Swagger needs to be at the latest version otherwise it will revert the changes to the previously generated version.

**Comment by poojamaiya** [comment]
Should we run `make get-deps` as part of the make build target all the time in order to avoid such inconsistencies?

**Comment by narehayrapetyan** [comment]
@poojamaiya Might be a good idea because travis is going to pull the latest swagger every time it does a build. Another option is to get a specific swagger version in get-deps. It doesn't seem a bad idea to get a release version instead of the latest commit on the dev branch.

**Comment by narehayrapetyan** [comment]
@poojamaiya opened an issue: https://github.com/blox/blox/issues/153

**Comment by poojamaiya** [comment]
Awesome. Thanks!
