### ISSUE TITLE
Replace ECS calls with calls to CSS in daemon scheduler

### ISSUE THREAD

**Issue by poojamaiya** [blox/blox#181]
Updates need to be done [here](https://github.com/blox/blox/blob/dev/daemon-scheduler/pkg/deployment/deployment_worker.go#L136)

**Comment by arminc** [comment]
The issue points to a non existing file (moved?). Is the issue relevant, close it?

**Comment by shubharao** [comment]
Assuming this is handled / not required in v1.0.

**Comment by narehayrapetyan** [comment]
actually we should move this to amazon-ecs-cluster-state-service
