### ISSUE TITLE
Directory to store Blox configuration information should start with .

### ISSUE THREAD

**Issue by arun-gupta** [blox/blox#190]
Starting up Blox locally creates `blox-state` directory in the home directory. The directory name is too invasive and does not follow best practices of using a `.` to hide any config directories.

This should instead be named something like `.blox` and then possibly a `state` directory inside it.

```
~ $ find blox-state/
blox-state/
blox-state//data
blox-state//data/member
blox-state//data/member/snap
blox-state//data/member/snap/db
blox-state//wal
blox-state//wal/0000000000000000-0000000000000000.wal
```

**Comment by ajosuarez** [comment]
good suggestion @arun-gupta. this is something we can consider changing in an upcoming release. thank you.
