### ISSUE TITLE
Cannot build cluster service

### ISSUE THREAD

**Issue by Khalian** [blox/blox#191]
main.go:20:2: cannot find package "github.com/cihub/seelog" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/cihub/seelog (from $GOROOT)
        /Users/arunavs/go/src/github.com/cihub/seelog (from $GOPATH)

This is after make get-deps and make.

**Comment by kylbarnes** [comment]
@Khalian The seelog dependency is located in the `/vendor/github.com/cihub/seelog/` directory inside Blox. From your output, it isn't looking for dependencies inside `/vendor` during build time. I know this behavior would happen if Blox is not built from within your $GOPATH. Please make sure you are building Blox from within $GOPATH/src. Let me know if that doesn't work for you.

**Comment by Khalian** [comment]
I wanted to build the service from some arbitrary location in the file system. Why do I have to be tied down to specific locations (e.g. under GOPATH)? Other projects do not have this problem.

**Comment by kylbarnes** [comment]
I did a quick Google search, and I don't think the vendor loaded dependencies (those in the `vendor` directory) will work in Go outside of the GOPATH. There might be some ways to accomplish what you're trying to do with symlinks, but I think it's probably easiest to keep the Blox source code in your GOPATH.

A couple applicable search results:
https://github.com/golang/go/issues/14566
https://github.com/Masterminds/glide/issues/150
http://stackoverflow.com/questions/37919668/golang-1-6-cannot-find-packages-in-vendor-folder

**Comment by Khalian** [comment]
It still does not build

arunavs at f45c89bd4dd3 in ~/go/blox/cluster-state-service on dev
$ pwd
/Users/arunavs/go/blox/cluster-state-service

arunavs at f45c89bd4dd3 in ~/go/blox/cluster-state-service on dev
$ echo $GOPATH
/Users/arunavs/go/

Generated licenses and copyrights
./scripts/build_binary.sh ./out
main.go:22:2: cannot find package "github.com/blox/blox/cluster-state-service/cmd" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/blox/blox/cluster-state-service/cmd (from $GOROOT)
        /Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/cmd (from $GOPATH)
main.go:23:2: cannot find package "github.com/blox/blox/cluster-state-service/config" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/blox/blox/cluster-state-service/config (from $GOROOT)
        /Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/config (from $GOPATH)
main.go:24:2: cannot find package "github.com/blox/blox/cluster-state-service/handler/run" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/blox/blox/cluster-state-service/handler/run (from $GOROOT)
        /Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/handler/run (from $GOPATH)
main.go:19:2: cannot find package "github.com/blox/blox/cluster-state-service/logger" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/blox/blox/cluster-state-service/logger (from $GOROOT)
        /Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/logger (from $GOPATH)
main.go:25:2: cannot find package "github.com/blox/blox/cluster-state-service/versioning" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/blox/blox/cluster-state-service/versioning (from $GOROOT)
        /Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/versioning (from $GOPATH)
main.go:20:2: cannot find package "github.com/cihub/seelog" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/cihub/seelog (from $GOROOT)
        /Users/arunavs/go/src/github.com/cihub/seelog (from $GOPATH)
make: *** [out/cluster-state-service] Error 1

What am I supposed to do now? 

A build system, by its very definition, should allow me to build a package from whereever I want. The fact that go needs to be under some filesystem directory is a substandard design choice in the first place. And even when I am inside the GOPATH hierarchy, it still does not work. 

More interestingly, what was the rationale for choosing Go of all languages for a pretty non trivial project like blox ?

**Comment by kylbarnes** [comment]
@Khalian Go is very picky about it's directory structure. It has to be in a specific location within the GOPATH. The actual make command should run out of `$GOPATH/src/github.com/blox/blox/cluster-state-service/`. Can you perform the following steps and let me know if they don't work for you?

```
$ mkdir -p $GOPATH/src/github.com/blox/
$ mv /Users/arunavs/go/blox $GOPATH/src/github.com/blox/
$ cd $GOPATH/src/github.com/blox/blox/cluster-state-service/
$ make
```

**Comment by Khalian** [comment]
No. I ran the commands to the letter. I got this error. 

Adding license for ./../../vendor/gopkg.in/yaml.v2
Adding license for ./../../vendor/google.golang.org/grpc
Generated licenses and copyrights
./scripts/build_binary.sh ./out
handler/api/v1/instanceapis.go:26:2: cannot find package "github.com/blox/blox/cluster-state-service/swagger/v1/generated/models" in any of:
        /Users/arunavs/go/src/github.com/blox/blox/vendor/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models (vendor tree)
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models (from $GOROOT)
        /Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models (from $GOPATH)
make: *** [out/cluster-state-service] Error 1

**Comment by Khalian** [comment]
@kylbarnes Hello ?

**Comment by kylbarnes** [comment]
@Khalian Sorry, missed your response. Right now it's erroring out with not being able to find `github.com/blox/blox/cluster-state-service/swagger/v1/generated/models`, which should be there. See the following link: [swagger models](https://github.com/blox/blox/tree/dev/cluster-state-service/swagger/v1/generated/models). This would only happen if those files don't exist in those directories that are being searched in your output. For those files specifically, it would be the last one: `/Users/arunavs/go/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models (from $GOPATH)`. Can you confirm that that directory does exist and contains the swagger models?

`$ ls $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models`

**Comment by Khalian** [comment]
ls $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models

ls: /Users/arunavs/go//src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models: No such file or directory

**Comment by kylbarnes** [comment]
Yup, that would be a problem. What is the closest parent directory you have?

```
$ ls $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/models/
$ ls $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated/
$ ls $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/
$ ls $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/
$ ls $GOPATH/src/github.com/blox/blox/cluster-state-service/
$ ls $GOPATH/src/github.com/blox/blox/
$ ls $GOPATH/src/github.com/blox/
$ ls $GOPATH/src/github.com/
$ ls $GOPATH/src/
```

**Comment by Khalian** [comment]
GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated is empty.

**Comment by kylbarnes** [comment]
I'm not sure why that folder was emptied on your side, but you will want to restore it via `git reset --hard`. After running that command, make sure the files in `$GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated` are restored.

My best guess is something version related on your side. I think the most likely culprit is going to be your swagger version, since that is what generates the files in that folder. Are you using the swagger located at `$GOPATH/bin/swagger` that was installed via `make get-deps`?

**Comment by Khalian** [comment]
@kylbarnes The git reset HEAD --hard command puts some stuff back into $GOPATH/src/github.com/blox/blox/cluster-state-service/swagger/v1/generated. Make get-deps also works. But make fails with the same issue post those command execs. 

I have no idea what swagger I am using. And by this point I don't really care. 

I am confused, why do I need to do all of these things for a simple make?

**Comment by Khalian** [comment]
You know what, I have lost interest in this project. I am closing the issue so that you guys can focus on more important things. @kylbarnes please fix your build system to actually run from anywhere (like any build system should).
