### ISSUE TITLE
blox serverless?

### ISSUE THREAD

**Issue by arminc** [blox/blox#199]
I am wondering if there is a reason not to make cluster-state-service and daemon-scheduler fully serverless? I was looking for the discussion about it but I could not find it, apologies if this is already addressed.

Running cluster-state-service and daemon-scheduler as Lambdas and replacing etcd with DynamoDB or another 'DB' as a service will result in a high available low-cost solution. The solution is very easy to maintain from the perspective of the user of Blox. 

The reason why ECS is interesting is because it removes the maintenance 'burden' of having to maintain the master nodes. Introducing blox with etcd brings the 'problem' back.

**Comment by narehayrapetyan** [comment]
@arminc Thank you for your question. That's a great point. We've heard that feedback before and realize that it's not easy to host the services on your side. To address those concerns we've put together a new design which you can look at [here.](https://github.com/blox/blox/blob/dev/docs/daemon_design.md)
