### ISSUE TITLE
Projects main programming language

### ISSUE THREAD

**Issue by arminc** [blox/blox#219]
I have been looking at https://github.com/blox/blox/pull/218 and I wondered if other languages besides Java where considered? 
I understand this is running on Lambda so it can not be Golang. And I also can understand choosing Java and not Python or JavaScript. But Java is "verbose" so using a different JVM language like Kotlin or Scala might be worth considering?  

I am not trying to start a language war but was wondering if verbosity of Java is a proper choice in this context?

**Comment by narehayrapetyan** [comment]
@arminc Java was chosen because it's a mature fully featured and well supported language and fits well with our existing ECS infrastructure.
