### ISSUE TITLE
Design top-level scheduler workflow

### ISSUE THREAD

**Issue by wjbuys** [blox/blox#258]
The core scheduling logic of Blox is a piece of code that looks at the current state of the cluster, and makes decisions on how to change the cluster state in order to meet some goal. These decisions eventually result in changes being made to the cluster (i.e. through ECS `runTask`/`terminateTask` API calls).

There are a couple of approaches we can take to translate the scheduling decisions into cluster state changes.

#### Single monolithic scheduler function making ECS calls
![image](https://user-images.githubusercontent.com/31602/30834854-e23583a2-a209-11e7-8f63-a0e7ee537f1b.png)
The option with the fewest moving parts, is to have each scheduling function immediately invoke the ECS `runTask`/`terminateTask` APIs when it determines that a task is not in the state it needs it to be in. This function is invoked on every change in cluster state and every change in deployment target state. This would allow it to rapidly respond to cluster state changes.

**Benefits:**
- simple to implement, few moving parts
- if ECS implements `restart=always`, this performs as well as the other solutions

**Drawbacks:**
- if a task fails to start, it will only be retried/restarted on the next scheduling loop
- if a task fails after a running for a while, it will only be retried/restarted on the next scheduling loop
- if the scheduling loop fails, or any of the `startTask` calls fail, it will only recover on the next iteration

#### Separate scheduler that delegates ECS API calls to subworkflows
![image](https://user-images.githubusercontent.com/31602/30834857-e8c8565e-a209-11e7-9b11-94cf5f160b3e.png)
Calls to ECS APIs might fail, and even when successfull may not have the desired effect (i.e. ending up with a Running task) because of task failures. A possible way to work around this, is to dispatch an asynchronous step functions workflow that will retry API calls until the desired state is reached, or a preset number of retries have failed.

**Benefits:**
- if a task fails to start, the subworkflow will retry it very quickly (doesn't have to wait for the next scheduling loop)

**Drawbacks:**
- would need to build some sort of idempotency on `startTask` workflows, so that schedulers don't try to start `Terminated` task again at the same time as the `startTask` workflow retries it
- if a task fails after a running for a while, it will only be retried/restarted on the next scheduling loop
- if the scheduling loop fails, or any of the `startTask` workflows fail, it will only recover on the next iteration

#### Separate scheduler generates desired state, subworkflows work to enact this state
![image](https://user-images.githubusercontent.com/31602/30834877-055bd0ac-a20a-11e7-90c6-b0620af27b85.png)

Another approach is to have schedulers make changes to some shared state that represents the overall "desired" state of the cluster, instead of taking any imperative action. Asynchronously, an operator workflow will diff the changes between the current state of the world and the desired state of the world, and dispatch the appropriate API calls to converge the current state to the desired state.

**Benefits:**
- if a task fails to start, the operator workflow will retry it very quickly (doesn't have to wait for the next scheduling loop)
- if a task fails after a while, the operator workflow will react quickly to the cluster state change and restart it (doesn't have to wait for the next scheduling loop)
- if a task started successfully, but the scheduling function reschedules it because its view of cluster state is out of date, we could ensure that no duplicates exist in the desired state through an idempotency key

**Drawbacks:**
- significantly more complex to build (need to design data store with idempotent API, additional workflows)
- duplicates concepts that already exist in the control plane (desired state)
- if control plane implements idempotency tokens or `restart=always`, then this no longer has any benefit

### Analysis
The last approach (i.e. using an intermediate "desired" state updated by the scheduler) feels nicely decoupled, and opens some interesting doors:
- If the shared store for desired state is transactional, schedulers can make decisions not only based on their observation of the current state of the world, but also on the desired state as expressed by other schedulers.
- Since the desired state is stored on a per-task/per-instance level, it's very easy to make the operator workflows only listen for changes in desired/actual state, and take local action to converge the state again. For example, the operator workflow receives an event that a task has failed (in the actual state). It looks at the desired state for the task, and sees that it should be running, so it calls `ECS.runTask` to rectify the situation immediately. By contrast, using a monolithic scheduling function above would mean that the task state change event would have to be fed through all schedulers so that the correct one can realize the task has failed and reschedule it.

This is more or less the way that the Kubernetes control plane works: instead of "running a task on an instance", you "bind a pod to a node", which will persistently try and keep that state current.

Furthermore, if we look closely at this solution, we can see that this is also what the ECS Control plane already does; it sets the desired state for a task based on the `runTask`/`terminateTask` call, and asynchronously reconciles this with the Agent. Why then would it be necessary for us to replicate this functionality that already exists?

It seems that the biggest gap right now that having our own view of desired cluster state would solve, is that we can't persistently schedule a task to a host, i.e. have it automatically restarted when it fails. If the control plane had this feature (which could be as simple as supporting `restart=always` as a flag to the agent), then the major benefits this approach fall away, as we can just treat the canonical ECS desired state as our desired state.

In that case, the last solution converges to look exactly like the "single monolithic scheduler" approach. So it seems we could get all the benefits of both approaches, if we can do some work in the control plane.

**Comment by narehayrapetyan** [comment]
> The option with the fewest moving parts, is to have each scheduling function immediately invoke the ECS runTask/terminateTask APIs

How does this work if there are thousands of tasks that need to be started? Is there some sort of breakdown?

> dispatch an asynchronous step functions workflow that will retry API calls until the desired state is reached, or a preset number of retries have failed.

One workflow that handles all the tasks?

> Another approach is to have schedulers make changes to some shared state that represents the overall "desired" state of the cluster, instead of taking any imperative action. 

All schedulers? Service, daemon etc? For every environment? Please expand.

**Comment by wjbuys** [comment]
Discussed this in person with @narehayrapetyan, will update the pros/cons in the issue body. The outcome was that we'll take the first option (using a single scheduling function that directly calls the ECS control plane in parallel), since that has the fewest moving parts, and the drawbacks are only in terms of performance impact which can be mitigated in the control plane through `restart=always` support.

**Comment by narehayrapetyan** [comment]
**Cluster State Retrieval** 

The scheduling workflows will be kicked off by 3 events: 

* cluster state changes received from the event stream
* cluster state reconciliation loops 
* deployment record changes when deployments are created

All of these events will be triggered on lambda. 

* event stream changes are received from cloud watch events and can invoke a lambda function to process them
* start deployment APIs will record a deployment in dynamodb and invoke a dynamodb stream that will be processed by lambda
* the reconciliation loops will be scheduled to run using the cron functionality in cloudwatch triggering a lambda function

For each event stream event we need to batch up a certain number of events to avoid starting a ECS poll loop every time we receive an event. We need to choose a long polling period. 

For reconciliation loops we need to retrieve all clusters that environments exist on and poll ECS for cluster state for that cluster. An optimization we will need to figure out is how to partition the environments into chunks so the loops are smaller. 

These events will kick off a getClusterState(cluster) lambda function. We need to ensure that getClusterState for each cluster is not invoked while another one is running for the same cluster.

How do we ensure that we don't run into throttling issues with ECS?

getClusterState queries ECS for the current state of the cluster and starts a scheduling workflow for every environment that lives on that cluster. The scheduling workflow is described above - it updates the deployment state and issues start/terminate task calls.

Figure out how to:
* subscribe to events for all customers
* batch up events for a period of time
* partition the scan for all clusters that have environments
* locking getClusterState per cluster run

**Comment by wjbuys** [comment]
I'll copy the above into #238, since that's what it mostly relates to
