### ISSUE TITLE
[Proposal] Support highly available Blox deployments

### ISSUE THREAD

**Issue by eswarbala** [blox/blox#47]
### Description
Currently Blox is a single instance application stack that can be run locally or orchestrated by ECS. In order to provide better resiliency to failures, every component in the Blox framework should be highly available. Blox is made of stateless services along with a stateful datastore. All the components should be configured to restart automatically upon exit in order to improve the reliability. Also the components should be run in a replicated manner to make them redundant, so that when one instance fails, others can take over the responsibility. Etcd, which is the datastore in the stack, should be setup to run in a clustered setup.

### Motivation
In order to improve the production readiness of Blox framework, single points of failure need to be eliminated and a redundant system design put in place to offer an acceptable level of uptime for the users.

### Use cases

* Able to achieve high degree of operational uptime when deploying Blox in production.

**Comment by jhspaybar** [comment]
Rather than having to maintain an available etcd cluster, I'd prefer to just run the data store on each node that needs the data and to allow for multiple nodes to consume the same event stream(maybe kinesis instead of sqs to support that).  Maybe both directions are valuable, but I'd prefer consumption from a kinesis stream with N consumers so that I don't have to maintain the etcd quorum.

**Comment by jhmartin** [comment]
@jhspaybar or perhaps store the data in a durable store such as dynanomodb or RDS, so that EC2 nodes do not to maintain quroum.

**Comment by shubharao** [comment]
Blox v1.0 is designed to be highly available. It will be built using other AWS services. See details in the [new design:](https://github.com/blox/blox/blob/dev/docs/daemon_design.md) sections [Service design](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#service-design) and [Availability](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#availability)
