### ISSUE TITLE
CloudWatch logs for daemon-scheduler

### ISSUE THREAD

**Issue by eswarbala** [blox/blox#63]
Add support for CloudWatch logs for cluster-state-service container.

**Comment by jhmartin** [comment]
Isn't this a docker configuration (the awslogs driver) ?

**Comment by narehayrapetyan** [comment]
Yes, @jhmartin, this is for the use-case where blox is not run in docker. Seems low priority since the default way to run it is in containers.

**Comment by shubharao** [comment]
In v1.0, we'll enable Cloudwatch logging for all Blox APIs to record an audit trail of operations. Design details are [here](https://github.com/blox/blox/blob/dev/docs/daemon_design.md).
