### ISSUE TITLE
[Proposal] Support for Kubernetes

### ISSUE THREAD

**Issue by iroller** [blox/blox#66]
# Description

This feature supports [Kubernetes](https://github.com/kubernetes/kubernetes/blob/master/docs/devel/scheduler.md) framework.

 It is currently possible to run [Kubernetes on AWS](http://kubernetes.io/docs/getting-started-guides/aws/) but the whole setup is complex and having it as a managed service integrated with AWS would be great.

EDIT: As it is mentioned in [comments](https://github.com/blox/blox/issues/66#issuecomment-264260530) supporting Kubernetes APIs is a better framing of this request.

# Motivation

Kubernetes is a very popular framework for running containers. It has a big community and tooling around it.

# Use cases

Allow the usage of Kubernetes container scheduler and any other of it's features that can fit into ECS.

**Comment by bigkraig** [comment]
👍

**Comment by josephjacks** [comment]
Great to see this issue. Thanks for creating @iroller. I have seen a huge # (200+) of customers and users of K8s ask for this.

**Comment by josephjacks** [comment]
@iroller I've seen a huge # of K8s users ask for this. Thanks.

Perhaps a better way of framing this request would be to build a first-class supported K8s API for all the app and cluster abstractions one could execute in ECS?

**Comment by isubuz** [comment]
@josephjacks Agree, from first thoughts, the idea of blox is not about K8s infrastructure and implementing *Kubernetes as a service*. If anything, the request should be about the API abstractions as rightly mentioned above.

**Comment by bacoboy** [comment]
Agreed.  k8s is a very different programming model from ECS (and schedulers like Mesos).

I can think of a couple people who'd be very interested in a hosted k8s AWS service, but I wouldn't hold my breath, but that isn't what Blox is trying to solve.   

Think of it more like:

ECS is to Mesos
as
Blox is to Marathon

My vote (if I had one) would be 👎  and close this...

**Comment by josephjacks** [comment]
@bacoboy By that logic this proposal makes even more sense. The Mesos world loves to tout their K8s framework.

**Comment by jason-riddle** [comment]
I'm assuming the silence means that this is not going to be supported? If so can this just be closed then?

**Comment by kylbarnes** [comment]
This is an interesting discussion.

The original post stated: `It is currently possible to run Kubernetes on AWS but the whole setup is complex and having it as a managed service integrated with AWS would be great`. To this, I would respond that Blox is not aiming to be an installation mechanism for Kubernetes. Blox is aimed at providing a framework for building custom schedulers on top of ECS. The analogy from @bacoboy is pretty good in stating that ECS is to Mesos, as Blox is to Marathon.

The other piece of this discussion here is whether to abstract and support the Kubernetes APIs. As of right now, this is outside the scope of Blox, as we are not trying to abstract Kubernetes. @iroller I’d probably recommend you post your original feature request on the AWS ECS forums, as I think this feature request falls more into the scope of ECS than to Blox.

**Comment by poojamaiya** [comment]
I'm closing this issue based on @kylbarnes response above. Please feel free to reopen if there are any more questions.
