### ISSUE TITLE
Support multiple data stores

### ISSUE THREAD

**Issue by djenriquez** [blox/blox#72]
Are there any plans for the cluster-state-service to support other data stores such as Consul?

On a side-note, is there a better place to ask questions like these?

**Comment by adam-finney** [comment]
It would be nice to see external datasources such as DynamoDB used.

**Comment by simplycloud** [comment]
@djenriquez we have discussed what it would take to make the data store pluggable. we decided to start with etcd, but we are open to supporting other data stores over time.

**Comment by djenriquez** [comment]
Is there a specific pattern that we as the community can follow and help add such data stores?

**Comment by kiranmeduri** [comment]
I would start [here](https://github.com/blox/blox/blob/dev/cluster-state-service/handler/store/datastore.go#L35). However at this point the configuration when starting cluster-state-service expects SQS and etcd. This configuration need to be generalized to support other event-streams (like kinesis #77) and stores (like DynamoDB, Consul).

**Comment by jhmartin** [comment]
As a cluster-management tool, it would be very useful for blox to store its data outside EC2 (such as RDS or dynamodb) -- something persistent that can survive EC2 failures.

**Comment by hridyeshpant** [comment]
@poojamaiya not sure why etcd is being used rather then using dynamodb. I deployed blox as ecs service and when ecs move this service to other ecs instances all old data got lost.
Do we support etcd as HA mode? 
we cant force ECS to run service in one particular instances always.is there any working solution to retain etcd data,

**Comment by poojamaiya** [comment]
@hridyeshpant Thanks for the feedback.

>> Do we support etcd as HA mode?

We have this in our roadmap and can be tracked [here](https://github.com/blox/blox/issues/47)

>> we cant force ECS to run service in one particular instances always.is there any working solution to retain etcd data.

The easiest way would be to force ECS to launch Blox on the same instance. You can do this by launching Blox on a cluster with a single instance. This is what the cloudformation template we provide does today.

Please let us know if this helps and/or if you have any more questions. Thank you!

**Comment by hridyeshpant** [comment]
@poojamaiya  even that wont work for long term. we need to update cluster with new ecs AMI.
 i saw there in blox 3.0 beta release .can we know what all change list in each release.
i dont think unless we can make etcd or other db as HA mode, blox can be used for production env, no one want non HA mode system to run in Production env. 
i tried to use efs to use blox ectd path .but seems blox etcd image is not allowing to put data /var/lib/etcd if mounted as efs.
is there any way we can use efs mount point for etcd ?

**Comment by pmanwatkar** [comment]
@hridyeshpant I had similar issue while setting up blox  cluster in ECS. I had to restart the docker service as the efs volume was not getting registered if you attach it to etcd docker container.

**Comment by xiang90** [comment]
@pmanwatkar @hridyeshpant 

this is the suggested way to run HA etcd on aws: https://github.com/coreos/etcd/blob/master/Documentation/platforms/aws.md. just in case you are interested.

**Comment by shubharao** [comment]
We have considered this feedback in the design of Blox v1.0. It is designed for HA as it uses other AWS services, it stores metadata in DynamoDB.  See design details [here](https://github.com/blox/blox/blob/dev/docs/daemon_design.md).
