### ISSUE TITLE
Generating `license.go` is non-deterministic

### ISSUE THREAD

**Issue by samuelkarp** [blox/blox#80]
It looks like generating `license.go` is non-deterministic; I get a different order when running on my Ubuntu laptop than what is checked in here.  `license.sh` does [shell globbing](https://github.com/blox/blox/blob/3f58577/daemon-scheduler/scripts/license.sh#L50) which can differ between machines.

**Comment by kylbarnes** [comment]
Logged as bug. Thanks for finding this.

**Comment by kylbarnes** [comment]
This has been resolved in #107.
