### ISSUE TITLE
update "deploy CFT on AWS" to infer available AZ using intrinsic function

### ISSUE THREAD

**Issue by asifamz** [blox/blox#88]
my first runs to get blox up on AWS failed due to mapping on the CFT, and it rolled back.
a more graceful experience  can be to use: 

"AvailabilityZone" : {
        "Fn::Select" : [ "0", { "Fn::GetAZs" : "" } ]
        },

The CFT will get the available AZ and CFT picks from them to create subnet,

**Comment by kylbarnes** [comment]
@asifamz can you paste the exact command you ran, and the reason for the failure? I'll try to duplicate on my side. Were you using an AWS account with administrator permissions, or an account with a locked down permission set?

**Comment by asifamz** [comment]
i ran aws --region <region> cloudformation create-stack --stack-name BloxLocal --template-body file://./deploy/docker/conf/cloudformation_template.json
 
at the time, i did not have a default VPC , the error was at the subnet creation step as it did not find the AZ in the mapping.

**Comment by kylbarnes** [comment]
@asifamz i don't think the region came through on that command. What region did you run it in? Also, `file://./deploy/docker/conf/cloudformation_template.json` does not create a subnet, so i'm a little unsure on how you got a subnet creation step failure when running that command. Are you sure you're not using the AWS CFT at `file://./deploy/aws/conf/cloudformation_template.json` instead? Can you elaborate on how to duplicate the issue?

**Comment by asifamz** [comment]
my bad, i was trying the AWS example

command: aws --region us-east-1 cloudformation create-stack --stack-name BloxAws --template-body file://./deploy/aws/conf/cloudformation_template.json --capabilities CAPABILITY_NAMED_IAM --parameters file:///tmp/blox_parameters.json

error: Subnet2	Value (us-east-1b) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: us-east-1c, us-east-1d, us-east-1a, us-east-1e.

**Comment by kylbarnes** [comment]
Thanks for finding this. This is legacy behavior specific to us-east-1 for older AWS accounts. I have incorporated the requested change and submitted PR #94. Once the PR gets merged, I'll close this as resolved. In the meantime @asifamz, you can just change `us-east-1b` to `us-east-1c` in the template, if you haven't already.

**Comment by kylbarnes** [comment]
Closing issue. This has been resolved in #94.
