### ISSUE TITLE
Support environment updates

### ISSUE THREAD

**Issue by michaelgruber** [blox/blox#91]
The daemon-scheduler api and demo cli don't seem to support updating environments. I've been deleting, stopping tasks manually, and recreating when I modify a task definition. Updating an environment to a new revision and having changes propagate to existing deployments would be useful.

**Comment by poojamaiya** [comment]
Thanks @michaelgruber. That is correct, the daemon scheduler today does not support updates to environments. We are currently working on a proposal to get this work started. Thanks for creating this issue.

**Comment by shubharao** [comment]
Handled in v1.0 design. See details [here](https://github.com/blox/blox/blob/dev/docs/daemon_design.md#updating-a-deployment)
